feature: ajout d'un champ de type date pour les formulaires personnalisés
atos-df-rennes/prevarisc pull request #157
Opened 2024-05-30 12:34 UTC by NazihAsmaa

2024-06-17 12:16 UTC, A709197 requested changes

2024-06-17 12:16 UTC, A709197 commented on application/views/scripts/calendrier-des-commissions/generationcompterendu.phtml
> +                                                                }
```suggestion
                                                            if ('Date' === $col['TYPE']) {
                                                                if (!empty($col['VALEUR'])) {
                                                                    $zendDate = new Zend_Date($col['VALEUR'], 'dd/MM/yyyy');
                                                                    $col['VALEUR'] = $zendDate->get(Zend_Date::DAY . ' ' . Zend_Date::MONTH_NAME . ' ' . Zend_Date::YEAR);
                                                                }else{
                                                                    $col['VALEUR']= "";
                                                                }
```

2024-06-17 12:16 UTC, A709197 commented on application/views/scripts/calendrier-des-commissions/generationcompterendu.phtml
> +                                                                if (!empty($champ['VALEUR'])) {
Si possible, éviter l'utilisation de la fonction `empty`

2024-06-17 12:16 UTC, A709197 commented on application/views/scripts/calendrier-des-commissions/generationconvoc.phtml
> +                                                }
Même commentaire que pour `generationcompterendu`

2024-06-17 12:16 UTC, A709197 commented on application/views/scripts/calendrier-des-commissions/generationodj.phtml
> +                                                }
Même commentaire que pour `generationcompterendu`

2024-06-17 12:16 UTC, A709197 commented on application/views/scripts/calendrier-des-commissions/generationpv.phtml
> +                                                                    }
Même commentaire que pour `generationcompterendu`

2024-06-17 12:16 UTC, A709197 commented on application/views/scripts/dossier/creationdoc.phtml
> +                                        }
Même commentaire que pour `generationcompterendu`

2024-06-17 12:36 UTC, A709197 reviewed
Ajouter des tests unitaires pour le service `Date.php`

2024-06-21 08:20 UTC, NazihAsmaa commented
Problèmes rencontrés :
Affichage incorrect des champs de fusion pour le champ parent.
Difficulté à sélectionner une date dans le datepicker associé au champ parent.

2024-06-24 09:45 UTC, A709197 approved these changes

2024-06-24 11:57 UTC, merged